/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const VideoPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'shares' : IDL.Nat,
  'username' : IDL.Text,
  'video' : ExternalBlob,
  'likes' : IDL.Nat,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'deletionTimestamp' : IDL.Opt(Time),
  'avatar' : IDL.Opt(IDL.Vec(IDL.Nat8)),
});
export const NotificationType = IDL.Variant({
  'like' : IDL.Record({ 'videoId' : IDL.Nat }),
  'share' : IDL.Record({ 'videoId' : IDL.Nat }),
  'reply' : IDL.Record({ 'videoId' : IDL.Nat }),
});
export const Notification = IDL.Record({
  'notificationType' : NotificationType,
  'recipient' : IDL.Principal,
  'isRead' : IDL.Bool,
  'sender' : IDL.Principal,
  'timestamp' : Time,
});
export const VideoReply = IDL.Record({
  'id' : IDL.Nat,
  'parentVideoId' : IDL.Nat,
  'creator' : IDL.Principal,
  'shares' : IDL.Nat,
  'username' : IDL.Text,
  'video' : ExternalBlob,
  'timestamp' : Time,
});
export const VisitorStats = IDL.Record({
  'allTime' : IDL.Nat,
  'monthly' : IDL.Nat,
  'daily' : IDL.Nat,
  'weekly' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelAccountDeletion' : IDL.Func([], [], []),
  'checkUsernameAvailability' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'createVideoPost' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Nat], []),
  'createVideoReply' : IDL.Func([IDL.Nat, ExternalBlob], [IDL.Nat], []),
  'deleteAccount' : IDL.Func([], [], []),
  'deleteVideoPost' : IDL.Func([IDL.Nat], [], []),
  'deleteVideoReply' : IDL.Func([IDL.Nat], [], []),
  'demoteUser' : IDL.Func([IDL.Principal], [], []),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getAccountDeletionTimeRemaining' : IDL.Func(
      [],
      [IDL.Opt(IDL.Int)],
      ['query'],
    ),
  'getActiveAccountsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getAllDeletionTimestamps' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Opt(Time)))],
      ['query'],
    ),
  'getAllVideoPosts' : IDL.Func([], [IDL.Vec(VideoPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFollowersAndFollowingCounts' : IDL.Func(
      [IDL.Principal],
      [IDL.Nat, IDL.Nat],
      ['query'],
    ),
  'getFollowersCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getFollowingCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPrincipalByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Principal)],
      ['query'],
    ),
  'getRepliesCountForPost' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getRepliesForPost' : IDL.Func([IDL.Nat], [IDL.Vec(VideoReply)], ['query']),
  'getRepliesForPostWithPagination' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Vec(VideoReply)],
      ['query'],
    ),
  'getReplyLikesCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getReplySharesCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getScheduledDeletions' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, Time))],
      ['query'],
    ),
  'getTotalVideoCounts' : IDL.Func([], [IDL.Nat, IDL.Nat], ['query']),
  'getUnreadNotificationsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserAccountDeletionTimeRemaining' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Int)],
      ['query'],
    ),
  'getUserFollowers' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getUserFollowing' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideoPostById' : IDL.Func([IDL.Nat], [IDL.Opt(VideoPost)], ['query']),
  'getVideoPostsByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(VideoPost)],
      ['query'],
    ),
  'getVideoRepliesByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(VideoReply)],
      ['query'],
    ),
  'getVideoReplyById' : IDL.Func([IDL.Nat], [IDL.Opt(VideoReply)], ['query']),
  'getVisitorStats' : IDL.Func([], [VisitorStats], ['query']),
  'hasUserLikedReply' : IDL.Func(
      [IDL.Nat, IDL.Principal],
      [IDL.Bool],
      ['query'],
    ),
  'hasUserLikedReplyForCaller' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFollowing' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Nat], [], []),
  'likeReply' : IDL.Func([IDL.Nat], [], []),
  'markNotificationsAsRead' : IDL.Func([], [], []),
  'performAutomatedAccountDeletion' : IDL.Func([], [], []),
  'permanentlyDeleteAccount' : IDL.Func([IDL.Principal], [], []),
  'promoteUser' : IDL.Func([IDL.Principal], [], []),
  'recordVisit' : IDL.Func([], [], []),
  'revalidateSession' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sharePost' : IDL.Func([IDL.Nat], [], []),
  'shareReply' : IDL.Func([IDL.Nat], [], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  'unlikeReply' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const VideoPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'shares' : IDL.Nat,
    'username' : IDL.Text,
    'video' : ExternalBlob,
    'likes' : IDL.Nat,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'deletionTimestamp' : IDL.Opt(Time),
    'avatar' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  });
  const NotificationType = IDL.Variant({
    'like' : IDL.Record({ 'videoId' : IDL.Nat }),
    'share' : IDL.Record({ 'videoId' : IDL.Nat }),
    'reply' : IDL.Record({ 'videoId' : IDL.Nat }),
  });
  const Notification = IDL.Record({
    'notificationType' : NotificationType,
    'recipient' : IDL.Principal,
    'isRead' : IDL.Bool,
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  const VideoReply = IDL.Record({
    'id' : IDL.Nat,
    'parentVideoId' : IDL.Nat,
    'creator' : IDL.Principal,
    'shares' : IDL.Nat,
    'username' : IDL.Text,
    'video' : ExternalBlob,
    'timestamp' : Time,
  });
  const VisitorStats = IDL.Record({
    'allTime' : IDL.Nat,
    'monthly' : IDL.Nat,
    'daily' : IDL.Nat,
    'weekly' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelAccountDeletion' : IDL.Func([], [], []),
    'checkUsernameAvailability' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'createVideoPost' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Nat], []),
    'createVideoReply' : IDL.Func([IDL.Nat, ExternalBlob], [IDL.Nat], []),
    'deleteAccount' : IDL.Func([], [], []),
    'deleteVideoPost' : IDL.Func([IDL.Nat], [], []),
    'deleteVideoReply' : IDL.Func([IDL.Nat], [], []),
    'demoteUser' : IDL.Func([IDL.Principal], [], []),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getAccountDeletionTimeRemaining' : IDL.Func(
        [],
        [IDL.Opt(IDL.Int)],
        ['query'],
      ),
    'getActiveAccountsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getAllDeletionTimestamps' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Opt(Time)))],
        ['query'],
      ),
    'getAllVideoPosts' : IDL.Func([], [IDL.Vec(VideoPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFollowersAndFollowingCounts' : IDL.Func(
        [IDL.Principal],
        [IDL.Nat, IDL.Nat],
        ['query'],
      ),
    'getFollowersCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getFollowingCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPrincipalByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Principal)],
        ['query'],
      ),
    'getRepliesCountForPost' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getRepliesForPost' : IDL.Func([IDL.Nat], [IDL.Vec(VideoReply)], ['query']),
    'getRepliesForPostWithPagination' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Vec(VideoReply)],
        ['query'],
      ),
    'getReplyLikesCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getReplySharesCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getScheduledDeletions' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, Time))],
        ['query'],
      ),
    'getTotalVideoCounts' : IDL.Func([], [IDL.Nat, IDL.Nat], ['query']),
    'getUnreadNotificationsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserAccountDeletionTimeRemaining' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Int)],
        ['query'],
      ),
    'getUserFollowers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getUserFollowing' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideoPostById' : IDL.Func([IDL.Nat], [IDL.Opt(VideoPost)], ['query']),
    'getVideoPostsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(VideoPost)],
        ['query'],
      ),
    'getVideoRepliesByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(VideoReply)],
        ['query'],
      ),
    'getVideoReplyById' : IDL.Func([IDL.Nat], [IDL.Opt(VideoReply)], ['query']),
    'getVisitorStats' : IDL.Func([], [VisitorStats], ['query']),
    'hasUserLikedReply' : IDL.Func(
        [IDL.Nat, IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'hasUserLikedReplyForCaller' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFollowing' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Nat], [], []),
    'likeReply' : IDL.Func([IDL.Nat], [], []),
    'markNotificationsAsRead' : IDL.Func([], [], []),
    'performAutomatedAccountDeletion' : IDL.Func([], [], []),
    'permanentlyDeleteAccount' : IDL.Func([IDL.Principal], [], []),
    'promoteUser' : IDL.Func([IDL.Principal], [], []),
    'recordVisit' : IDL.Func([], [], []),
    'revalidateSession' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sharePost' : IDL.Func([IDL.Nat], [], []),
    'shareReply' : IDL.Func([IDL.Nat], [], []),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
    'unlikeReply' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };