/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Notification {
  'notificationType' : NotificationType,
  'recipient' : Principal,
  'isRead' : boolean,
  'sender' : Principal,
  'timestamp' : Time,
}
export type NotificationType = { 'like' : { 'videoId' : bigint } } |
  { 'share' : { 'videoId' : bigint } } |
  { 'reply' : { 'videoId' : bigint } };
export type Time = bigint;
export interface UserProfile {
  'username' : string,
  'deletionTimestamp' : [] | [Time],
  'avatar' : [] | [Uint8Array],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoPost {
  'id' : bigint,
  'title' : string,
  'creator' : Principal,
  'shares' : bigint,
  'username' : string,
  'video' : ExternalBlob,
  'likes' : bigint,
  'timestamp' : Time,
}
export interface VideoReply {
  'id' : bigint,
  'parentVideoId' : bigint,
  'creator' : Principal,
  'shares' : bigint,
  'username' : string,
  'video' : ExternalBlob,
  'timestamp' : Time,
}
export interface VisitorStats {
  'allTime' : bigint,
  'monthly' : bigint,
  'daily' : bigint,
  'weekly' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelAccountDeletion' : ActorMethod<[], undefined>,
  'checkUsernameAvailability' : ActorMethod<[string], boolean>,
  'createVideoPost' : ActorMethod<[string, ExternalBlob], bigint>,
  'createVideoReply' : ActorMethod<[bigint, ExternalBlob], bigint>,
  'deleteAccount' : ActorMethod<[], undefined>,
  'deleteVideoPost' : ActorMethod<[bigint], undefined>,
  'deleteVideoReply' : ActorMethod<[bigint], undefined>,
  'demoteUser' : ActorMethod<[Principal], undefined>,
  'followUser' : ActorMethod<[Principal], undefined>,
  'getAccountDeletionTimeRemaining' : ActorMethod<[], [] | [bigint]>,
  'getActiveAccountsCount' : ActorMethod<[], bigint>,
  'getAllDeletionTimestamps' : ActorMethod<[], Array<[Principal, [] | [Time]]>>,
  'getAllVideoPosts' : ActorMethod<[], Array<VideoPost>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDonateText' : ActorMethod<[], string>,
  'getFollowersAndFollowingCounts' : ActorMethod<[Principal], [bigint, bigint]>,
  'getFollowersCount' : ActorMethod<[Principal], bigint>,
  'getFollowingCount' : ActorMethod<[Principal], bigint>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPrincipalByUsername' : ActorMethod<[string], [] | [Principal]>,
  'getRepliesCountForPost' : ActorMethod<[bigint], bigint>,
  'getRepliesForPost' : ActorMethod<[bigint], Array<VideoReply>>,
  'getRepliesForPostWithPagination' : ActorMethod<
    [bigint, bigint, bigint],
    Array<VideoReply>
  >,
  'getReplyLikesCount' : ActorMethod<[bigint], bigint>,
  'getReplySharesCount' : ActorMethod<[bigint], bigint>,
  'getScheduledDeletions' : ActorMethod<[], Array<[Principal, Time]>>,
  'getTotalVideoCounts' : ActorMethod<[], [bigint, bigint]>,
  'getUnreadNotificationsCount' : ActorMethod<[], bigint>,
  'getUserAccountDeletionTimeRemaining' : ActorMethod<
    [Principal],
    [] | [bigint]
  >,
  'getUserFollowers' : ActorMethod<[Principal], Array<Principal>>,
  'getUserFollowing' : ActorMethod<[Principal], Array<Principal>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideoPostById' : ActorMethod<[bigint], [] | [VideoPost]>,
  'getVideoPostsByUser' : ActorMethod<[Principal], Array<VideoPost>>,
  'getVideoRepliesByUser' : ActorMethod<[Principal], Array<VideoReply>>,
  'getVideoReplyById' : ActorMethod<[bigint], [] | [VideoReply]>,
  'getVisitorStats' : ActorMethod<[], VisitorStats>,
  'hasUserLikedReply' : ActorMethod<[bigint, Principal], boolean>,
  'hasUserLikedReplyForCaller' : ActorMethod<[bigint], boolean>,
  'isAdmin' : ActorMethod<[Principal], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFollowing' : ActorMethod<[Principal], boolean>,
  'likePost' : ActorMethod<[bigint], undefined>,
  'likeReply' : ActorMethod<[bigint], undefined>,
  'markNotificationsAsRead' : ActorMethod<[], undefined>,
  'performAutomatedAccountDeletion' : ActorMethod<[], undefined>,
  'permanentlyDeleteAccount' : ActorMethod<[Principal], undefined>,
  'promoteUser' : ActorMethod<[Principal], undefined>,
  'recordVisit' : ActorMethod<[], undefined>,
  'revalidateSession' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setDonateText' : ActorMethod<[string], undefined>,
  'sharePost' : ActorMethod<[bigint], undefined>,
  'shareReply' : ActorMethod<[bigint], undefined>,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
  'unlikeReply' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];