/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type NotificationType = {
    __kind__: "like";
    like: {
        videoId: bigint;
    };
} | {
    __kind__: "share";
    share: {
        videoId: bigint;
    };
} | {
    __kind__: "reply";
    reply: {
        videoId: bigint;
    };
};
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface VideoReply {
    id: bigint;
    parentVideoId: bigint;
    creator: Principal;
    shares: bigint;
    username: string;
    video: ExternalBlob;
    timestamp: Time;
}
export interface Notification {
    notificationType: NotificationType;
    recipient: Principal;
    isRead: boolean;
    sender: Principal;
    timestamp: Time;
}
export interface VideoPost {
    id: bigint;
    title: string;
    creator: Principal;
    shares: bigint;
    username: string;
    video: ExternalBlob;
    likes: bigint;
    timestamp: Time;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface VisitorStats {
    allTime: bigint;
    monthly: bigint;
    daily: bigint;
    weekly: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    username: string;
    deletionTimestamp?: Time;
    avatar?: Uint8Array;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelAccountDeletion(): Promise<void>;
    checkUsernameAvailability(username: string): Promise<boolean>;
    createVideoPost(_title: string, video: ExternalBlob): Promise<bigint>;
    createVideoReply(parentVideoId: bigint, video: ExternalBlob): Promise<bigint>;
    deleteAccount(): Promise<void>;
    deleteVideoPost(postId: bigint): Promise<void>;
    deleteVideoReply(replyId: bigint): Promise<void>;
    demoteUser(adminToRemove: Principal): Promise<void>;
    followUser(target: Principal): Promise<void>;
    getAccountDeletionTimeRemaining(): Promise<bigint | null>;
    getActiveAccountsCount(): Promise<bigint>;
    getAllDeletionTimestamps(): Promise<Array<[Principal, Time | null]>>;
    getAllVideoPosts(): Promise<Array<VideoPost>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFollowersAndFollowingCounts(user: Principal): Promise<[bigint, bigint]>;
    getFollowersCount(_user: Principal): Promise<bigint>;
    getFollowingCount(_user: Principal): Promise<bigint>;
    getNotifications(): Promise<Array<Notification>>;
    getPrincipalByUsername(username: string): Promise<Principal | null>;
    getRepliesCountForPost(videoId: bigint): Promise<bigint>;
    getRepliesForPost(_videoId: bigint): Promise<Array<VideoReply>>;
    getRepliesForPostWithPagination(videoId: bigint, startIndex: bigint, batchSize: bigint): Promise<Array<VideoReply>>;
    getReplyLikesCount(replyId: bigint): Promise<bigint>;
    getReplySharesCount(replyId: bigint): Promise<bigint>;
    getScheduledDeletions(): Promise<Array<[Principal, Time]>>;
    getTotalVideoCounts(): Promise<[bigint, bigint]>;
    getUnreadNotificationsCount(): Promise<bigint>;
    getUserAccountDeletionTimeRemaining(_user: Principal): Promise<bigint | null>;
    getUserFollowers(_user: Principal): Promise<Array<Principal>>;
    getUserFollowing(_user: Principal): Promise<Array<Principal>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVideoPostById(id: bigint): Promise<VideoPost | null>;
    getVideoPostsByUser(user: Principal): Promise<Array<VideoPost>>;
    getVideoRepliesByUser(user: Principal): Promise<Array<VideoReply>>;
    getVideoReplyById(id: bigint): Promise<VideoReply | null>;
    getVisitorStats(): Promise<VisitorStats>;
    hasUserLikedReply(replyId: bigint, user: Principal): Promise<boolean>;
    hasUserLikedReplyForCaller(replyId: bigint): Promise<boolean>;
    isAdmin(user: Principal): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isFollowing(target: Principal): Promise<boolean>;
    likePost(postId: bigint): Promise<void>;
    likeReply(replyId: bigint): Promise<void>;
    markNotificationsAsRead(): Promise<void>;
    performAutomatedAccountDeletion(): Promise<void>;
    permanentlyDeleteAccount(target: Principal): Promise<void>;
    promoteUser(newAdmin: Principal): Promise<void>;
    recordVisit(): Promise<void>;
    revalidateSession(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sharePost(postId: bigint): Promise<void>;
    shareReply(replyId: bigint): Promise<void>;
    unfollowUser(target: Principal): Promise<void>;
    unlikeReply(replyId: bigint): Promise<void>;
}
import type { ExternalBlob as _ExternalBlob, Notification as _Notification, NotificationType as _NotificationType, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, VideoPost as _VideoPost, VideoReply as _VideoReply, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelAccountDeletion(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelAccountDeletion();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelAccountDeletion();
            return result;
        }
    }
    async checkUsernameAvailability(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkUsernameAvailability(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkUsernameAvailability(arg0);
            return result;
        }
    }
    async createVideoPost(arg0: string, arg1: ExternalBlob): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createVideoPost(arg0, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVideoPost(arg0, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createVideoReply(arg0: bigint, arg1: ExternalBlob): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createVideoReply(arg0, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVideoReply(arg0, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteAccount(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAccount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAccount();
            return result;
        }
    }
    async deleteVideoPost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVideoPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVideoPost(arg0);
            return result;
        }
    }
    async deleteVideoReply(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVideoReply(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVideoReply(arg0);
            return result;
        }
    }
    async demoteUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.demoteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.demoteUser(arg0);
            return result;
        }
    }
    async followUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.followUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followUser(arg0);
            return result;
        }
    }
    async getAccountDeletionTimeRemaining(): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccountDeletionTimeRemaining();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccountDeletionTimeRemaining();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveAccountsCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveAccountsCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveAccountsCount();
            return result;
        }
    }
    async getAllDeletionTimestamps(): Promise<Array<[Principal, Time | null]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDeletionTimestamps();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDeletionTimestamps();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllVideoPosts(): Promise<Array<VideoPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVideoPosts();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVideoPosts();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowersAndFollowingCounts(arg0: Principal): Promise<[bigint, bigint]> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowersAndFollowingCounts(arg0);
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowersAndFollowingCounts(arg0);
            return [
                result[0],
                result[1]
            ];
        }
    }
    async getFollowersCount(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowersCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowersCount(arg0);
            return result;
        }
    }
    async getFollowingCount(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowingCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowingCount(arg0);
            return result;
        }
    }
    async getNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrincipalByUsername(arg0: string): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrincipalByUsername(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrincipalByUsername(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRepliesCountForPost(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getRepliesCountForPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRepliesCountForPost(arg0);
            return result;
        }
    }
    async getRepliesForPost(arg0: bigint): Promise<Array<VideoReply>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRepliesForPost(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRepliesForPost(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRepliesForPostWithPagination(arg0: bigint, arg1: bigint, arg2: bigint): Promise<Array<VideoReply>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRepliesForPostWithPagination(arg0, arg1, arg2);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRepliesForPostWithPagination(arg0, arg1, arg2);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReplyLikesCount(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getReplyLikesCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReplyLikesCount(arg0);
            return result;
        }
    }
    async getReplySharesCount(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getReplySharesCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReplySharesCount(arg0);
            return result;
        }
    }
    async getScheduledDeletions(): Promise<Array<[Principal, Time]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScheduledDeletions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScheduledDeletions();
            return result;
        }
    }
    async getTotalVideoCounts(): Promise<[bigint, bigint]> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalVideoCounts();
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalVideoCounts();
            return [
                result[0],
                result[1]
            ];
        }
    }
    async getUnreadNotificationsCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadNotificationsCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadNotificationsCount();
            return result;
        }
    }
    async getUserAccountDeletionTimeRemaining(arg0: Principal): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserAccountDeletionTimeRemaining(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserAccountDeletionTimeRemaining(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserFollowers(arg0: Principal): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserFollowers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserFollowers(arg0);
            return result;
        }
    }
    async getUserFollowing(arg0: Principal): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserFollowing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserFollowing(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideoPostById(arg0: bigint): Promise<VideoPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoPostById(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoPostById(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideoPostsByUser(arg0: Principal): Promise<Array<VideoPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoPostsByUser(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoPostsByUser(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideoRepliesByUser(arg0: Principal): Promise<Array<VideoReply>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoRepliesByUser(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoRepliesByUser(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideoReplyById(arg0: bigint): Promise<VideoReply | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoReplyById(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoReplyById(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVisitorStats(): Promise<VisitorStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisitorStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisitorStats();
            return result;
        }
    }
    async hasUserLikedReply(arg0: bigint, arg1: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasUserLikedReply(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasUserLikedReply(arg0, arg1);
            return result;
        }
    }
    async hasUserLikedReplyForCaller(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasUserLikedReplyForCaller(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasUserLikedReplyForCaller(arg0);
            return result;
        }
    }
    async isAdmin(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isFollowing(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isFollowing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isFollowing(arg0);
            return result;
        }
    }
    async likePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likePost(arg0);
            return result;
        }
    }
    async likeReply(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likeReply(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeReply(arg0);
            return result;
        }
    }
    async markNotificationsAsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationsAsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationsAsRead();
            return result;
        }
    }
    async performAutomatedAccountDeletion(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.performAutomatedAccountDeletion();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.performAutomatedAccountDeletion();
            return result;
        }
    }
    async permanentlyDeleteAccount(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.permanentlyDeleteAccount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.permanentlyDeleteAccount(arg0);
            return result;
        }
    }
    async promoteUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.promoteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.promoteUser(arg0);
            return result;
        }
    }
    async recordVisit(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordVisit();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordVisit();
            return result;
        }
    }
    async revalidateSession(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.revalidateSession();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revalidateSession();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sharePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sharePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sharePost(arg0);
            return result;
        }
    }
    async shareReply(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.shareReply(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.shareReply(arg0);
            return result;
        }
    }
    async unfollowUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowUser(arg0);
            return result;
        }
    }
    async unlikeReply(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikeReply(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikeReply(arg0);
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_NotificationType_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
async function from_candid_VideoPost_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoPost): Promise<VideoPost> {
    return await from_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function from_candid_VideoReply_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoReply): Promise<VideoReply> {
    return await from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VideoPost]): Promise<VideoPost | null> {
    return value.length === 0 ? null : await from_candid_VideoPost_n16(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VideoReply]): Promise<VideoReply | null> {
    return value.length === 0 ? null : await from_candid_VideoReply_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    creator: Principal;
    shares: bigint;
    username: string;
    video: _ExternalBlob;
    likes: bigint;
    timestamp: _Time;
}): Promise<{
    id: bigint;
    title: string;
    creator: Principal;
    shares: bigint;
    username: string;
    video: ExternalBlob;
    likes: bigint;
    timestamp: Time;
}> {
    return {
        id: value.id,
        title: value.title,
        creator: value.creator,
        shares: value.shares,
        username: value.username,
        video: await from_candid_ExternalBlob_n18(_uploadFile, _downloadFile, value.video),
        likes: value.likes,
        timestamp: value.timestamp
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    deletionTimestamp: [] | [_Time];
    avatar: [] | [Uint8Array];
}): {
    username: string;
    deletionTimestamp?: Time;
    avatar?: Uint8Array;
} {
    return {
        username: value.username,
        deletionTimestamp: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.deletionTimestamp)),
        avatar: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.avatar))
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notificationType: _NotificationType;
    recipient: Principal;
    isRead: boolean;
    sender: Principal;
    timestamp: _Time;
}): {
    notificationType: NotificationType;
    recipient: Principal;
    isRead: boolean;
    sender: Principal;
    timestamp: Time;
} {
    return {
        notificationType: from_candid_NotificationType_n28(_uploadFile, _downloadFile, value.notificationType),
        recipient: value.recipient,
        isRead: value.isRead,
        sender: value.sender,
        timestamp: value.timestamp
    };
}
async function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    parentVideoId: bigint;
    creator: Principal;
    shares: bigint;
    username: string;
    video: _ExternalBlob;
    timestamp: _Time;
}): Promise<{
    id: bigint;
    parentVideoId: bigint;
    creator: Principal;
    shares: bigint;
    username: string;
    video: ExternalBlob;
    timestamp: Time;
}> {
    return {
        id: value.id,
        parentVideoId: value.parentVideoId,
        creator: value.creator,
        shares: value.shares,
        username: value.username,
        video: await from_candid_ExternalBlob_n18(_uploadFile, _downloadFile, value.video),
        timestamp: value.timestamp
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_tuple_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, [] | [_Time]]): [Principal, Time | null] {
    return [
        value[0],
        from_candid_opt_n14(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    like: {
        videoId: bigint;
    };
} | {
    share: {
        videoId: bigint;
    };
} | {
    reply: {
        videoId: bigint;
    };
}): {
    __kind__: "like";
    like: {
        videoId: bigint;
    };
} | {
    __kind__: "share";
    share: {
        videoId: bigint;
    };
} | {
    __kind__: "reply";
    reply: {
        videoId: bigint;
    };
} {
    return "like" in value ? {
        __kind__: "like",
        like: value.like
    } : "share" in value ? {
        __kind__: "share",
        share: value.share
    } : "reply" in value ? {
        __kind__: "reply",
        reply: value.reply
    } : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, [] | [_Time]]>): Array<[Principal, Time | null]> {
    return value.map((x)=>from_candid_tuple_n13(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VideoPost>): Promise<Array<VideoPost>> {
    return await Promise.all(value.map(async (x)=>await from_candid_VideoPost_n16(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n26(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VideoReply>): Promise<Array<VideoReply>> {
    return await Promise.all(value.map(async (x)=>await from_candid_VideoReply_n32(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_UserProfile_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    deletionTimestamp?: Time;
    avatar?: Uint8Array;
}): {
    username: string;
    deletionTimestamp: [] | [_Time];
    avatar: [] | [Uint8Array];
} {
    return {
        username: value.username,
        deletionTimestamp: value.deletionTimestamp ? candid_some(value.deletionTimestamp) : candid_none(),
        avatar: value.avatar ? candid_some(value.avatar) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
